### ISSUE TITLE
Game-breaking bug in v1.11.0

### ISSUE THREAD

**Issue by electrum-bowie** [CesiumGS/cesium-unity#476]
I'm not at my computer right now, but I'm just making sure that you guys are aware, I don't have the error logs because I instantly downgraded to the previous one and I didn't have time to do anything else that day either way.

The error logs had to do with something related to 'ellipsoid', and each time I tried to write to the 'longitudeLatitudeHeight' property the code failed with that error in the console, completely breaking my project...

**Comment by electrum-bowie** [comment]
If you aren't aware of this, I'll continue providing info here when I get the chance

**Comment by j9liu** [comment]
Hey @electrum-bowie, thanks for letting us know. Can you provide step-by-step instructions for reproducing the error? It would help us to have a minimal reproducible example.

**Comment by electrum-bowie** [comment]
> The error logs had to do with something related to 'ellipsoid', **and each time I tried to write to the 'longitudeLatitudeHeight' property the code failed with that error in the console**, completely breaking my project...

**Comment by azrogers** [comment]
@electrum-bowie Do you mean setting the `longitudeLatitudeHeight` property on a `CesiumGlobeAnchor`? I've tried setting this property in the latest version of Cesium for Unity and I'm not able to reproduce this bug. Could you share a sample of the code you were using that was causing this issue?

**Comment by electrum-bowie** [comment]
Through code, of course setting it through the UI would work

**Comment by azrogers** [comment]
Setting it through the inspector calls the same method as setting it from code, so I'm not sure it's "of course." 😉 Regardless, I tested with a script. This is the script I used:
```
using CesiumForUnity;
using System.Collections;
using System.Collections.Generic;
using Unity.Mathematics;
using UnityEngine;

public class Test : MonoBehaviour
{
    // Update is called once per frame
    void Update()
    {
        var anchor = GetComponent<CesiumGlobeAnchor>();
        anchor.longitudeLatitudeHeight = double3.zero;
    }
}
```

If you run this in your project on Cesium 1.11.0, does this cause an issue?

**Comment by azrogers** [comment]
@electrum-bowie Are you still experiencing this issue?

**Comment by electrum-bowie** [comment]
seems like the issue is now gone

**Comment by electrum-bowie** [comment]
Nope, here it is:
![image](https://github.com/user-attachments/assets/cffb1e07-9e95-4156-9b21-7281b825c236)
![Uploading image.png…]()

**Comment by electrum-bowie** [comment]
after running:

```cs
    private void LoadSavedVectorLastLocation()
    {
        double x = PlayerPrefs.GetFloat("VectorLastLocationX", 0);
        double y = PlayerPrefs.GetFloat("VectorLastLocationY", 0);
        double z = PlayerPrefs.GetFloat("VectorLastLocationZ", 0);

        if (x != 0 && y != 0 && z != 0)
        {
            cesiumAnchor.longitudeLatitudeHeight = new double3(x, y, z);
        }
    }
```

at Start();

**Comment by azrogers** [comment]
I see the issue - if the globe anchor is disabled, `_georeference` will be null, so that line will fail. I've created a PR for a fix.

**Comment by electrum-bowie** [comment]
Perfect !

**Comment by kring** [comment]
Fixed in #480.

**Comment by electrum-bowie** [comment]
Unfortunately that did not fix it, the issue still occurs using the latest cesium unity package version as of today..

**Comment by electrum-bowie** [comment]
I still have to use v1.10 to continue using my existing workflow.

**Comment by kring** [comment]
@electrum-bowie please help us reproduce this issue so that we can fix it. Perhaps you can provide a minimal project that reproduces the issue?

**Comment by electrum-bowie** [comment]
I've worked around it with a hacky solution since that error has indeed been solved.

The solution was to set it consistently until the anchor has been moved.

**Comment by electrum-bowie** [comment]
Really weird, 2 versions ago everything was fine, setting it once did the job
