### ISSUE TITLE
Unity crashes with bad allocation when loading tile

### ISSUE THREAD

**Issue by charlotte-pbt** [CesiumGS/cesium-unity#553]
I use Cesium in AR on a Hololens 2 headset, and after several minutes of play Unity crashes with bad allocation when loading tile. I have the impression that the problem is a memory leak in the tileset cache, because it happened as soon as I increased it.

This is the error I found in the logs : 

``
[error] [TilesetContentManager.cpp:1120] An unexpected error occurs when loading tile: bad allocation
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Reinterop.ReinteropInitializer:UnityEngine_Debug_CallLog_FA05wu8x__otZNsgdHTnU9A(IntPtr, IntPtr*)
CesiumForUnity.Cesium3DTileset:Update()]
``

**Comment by kring** [comment]
It's very likely this was fixed in Cesium for Unity v1.15.4 with the change to unload external tilesets. Can you please try it and let us know?

**Comment by charlotte-pbt** [comment]
Thank's for your reply, we were already on v1.15.4 and currently we are on v1.15.5 but the problem still presist.

**Comment by kring** [comment]
Ok, thank you for trying out the new version.

Re-reading your top post, I noticed that you mentioned that you increased the tileset cache. What have you increased it to? If increasing the cache size causes a bad alloc (which I believe is an "out of memory" error), then it probably indicates that you've set it too high for the available memory on the device. The purpose of the tileset cache is, by definition, to hold extra tiles that are unused, in case they are used again later. To minimize memory usage, set it to zero.

I can't promise there is no memory leak, but we don't currently know of one. The first step if you suspect one is to eliminate the non-leak sources of memory growth, such as an overly large cache limit.

**Comment by j9liu** [comment]
Hi @charlotte-pbt, is this still an issue for you today? If so, did you see Kevin's response above?

**Comment by j9liu** [comment]
I'm going to close this due to inactivity, but please reopen if this is still an issue today!
